name: checkmate

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_secure_storage: ^11.2.0
  qr_flutter: ^4.1.0
  pdf: ^3.13.1
  printing: ^5.15.1
  qr: ^3.0.2

  # Camera scanning
  camera: ^0.12.1
  file_selector: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


